### ISSUE TITLE
'clean up' not working properly

### ISSUE THREAD

**Issue by romnempire** [rix0rrr/WindowsPathEditor#12]
i ran 'clean up' then 'save', which did not clean a directory marked as nonexistent from the userpath, but appended the string ' \user C\Program' to the end of my system path.  would try to replicate, but i don't really want to mess up my path.

**Comment by rix0rrr** [comment]
Can't really reproduce this. Do you have more information?

**Comment by rix0rrr** [comment]
Closing for lack of response. Reopen if necessary.
