### ISSUE TITLE
Show a diff of path entries before saving

### ISSUE THREAD

**Issue by APerson241** [rix0rrr/WindowsPathEditor#14]
It would be great if a window popped up when you hit "Save" that said what files would be added and which ones would be removed. Something like this highly professional MS Paint mockup:

![windows-path-editor-confirm-diff](https://cloud.githubusercontent.com/assets/1981364/7105756/a99dbee6-e0f6-11e4-8337-79d2e6300dd4.png)

**Comment by rix0rrr** [comment]
Fixed in the latest release
