### ISSUE TITLE
Drag n'drop not working anymore after reordering items

### ISSUE THREAD

**Issue by odalet** [rix0rrr/WindowsPathEditor#18]
Steps to reproduce:
* Drag a few files/dirs from explorer to the system path listbox: works
* Reorder the listbox items (drag/drop): works
* Now, try to drag a dir from explorer: does not work any more...

I've forked and spotted the place where things go badly: in `DraggedAdorner.SetPosition` an exception is raised that says **Cannot access adorners on element that has no adorners**. This is what stops dragging from working. I've found that simply eating the exception seems to solve things. So a better fix may be what's proposed here: http://stackoverflow.com/questions/8655814/cannot-access-adorners-on-element-that-has-no-adorners 

As soon as my old VS2010 is updated with nuget manager, I'll fix this that way and submit to you a pull request.

**Comment by rix0rrr** [comment]
Fix released as 1.6, thanks
