### ISSUE TITLE
Add directory by typing it

### ISSUE THREAD

**Issue by ezk84** [rix0rrr/WindowsPathEditor#21]
Often I have to enter path variables that I've copy-pasted, it would be easier if I could just enter it by typing it rather than searching in the file dialog. 

Thanks for the app!

**Comment by rix0rrr** [comment]
You can also navigate to the directory in Explorer and just drag it in.

However, I had a change contributed by @odalet lying around that added an edit box for you to paste the path into, so I just released that as 1.7.
