### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by geckoseo** [rix0rrr/WindowsPathEditor#22]
Hey, great idea, I have used the [Path Editor](http://patheditor2.codeplex.com/) tool in the past,but it was getting flagged as unsafe by my AV.

Recently upgraded to Windows 10, so I am looking for a better option that the one in the link above. 

So my three questions are, is WindowsPathEditor recognised as "friendly" by Windows, is it secure, and does it work with Windows 10?

Many thanks!

**Comment by rix0rrr** [comment]
Hi Guy,

Really couldn't tell you, as I'm not using Windows 10 myself. I'd say: go ahead and try it out! It'll only be a couple of minutes of your time.

(When you do, please tell me the result of your test! Much appreciated)

**Comment by skfd** [comment]
It does work.

**Comment by geckoseo** [comment]
Hi, yes, it works just fine
